# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ba3bc6fd94b3ecf783f8dc6dab57e766da662c801efc12486e132e1584b72259abcddfe59a1e8c67168742252c34b1f4f7f403d96478086d231c2ee7b21780

test:
  secret_key_base: 029c01ab9b569418a65255184a36feda976bd54d96c5a73f4a32e522b6721bab1922b4dc1c713d9d6cc678c9929ecf4de59d8838317751a25a82989c1b699da9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
